packages:
  - slides/*

allowBuilds:
  esbuild: false
  playwright-chromium: false
  sharp: false
  workerd: false

catalog:
  '@slidev/cli': 52.15.0
  '@slidev/theme-default': 0.25.0
  playwright-chromium: 1.60.0
